os: osx
language: swift
osx_image: xcode11
env:
- DESTINATION="OS=13.0,name=iPhone 11" SCHEME="SwiftRSA" SDK=iphonesimulator CODECOV_TOKEN=e58b9c26-6fc1-4b87-be77-0b6a88f37f3c
script:
  xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test
after_success:
  - bash <(curl -s https://codecov.io/bash) -F SwiftRSA
notifications:
  email:
    - 11@boxue.io
